variable "tenant_id" {
  description = "Client tenant ID"
  type        = string
}

variable "object_id" {
  description = "Object ID of the component that is accessing the key vault"
  type        = string
}
variable "resource_group_name" {
  description = "Name of the Resource Group where the MSSQL resources will reside."
  type        = string
}

variable "location" {
  description = "Azure region for the MSSQL resources."
  type        = string
}

variable "tags" {
  description = "Tags applied to all resources created by this module."
  type        = map(string)
  default     = {}
}

variable "sql_version" {
  description = "sql Version."
  type        = string
}

variable "sql_server_name" {
  description = "Globally‑unique name for the Azure MSSQL Server (do **not** include the domain)."
  type        = string
}

variable "administrator_login" {
  description = "Administrator username for the MSSQL Server."
  type        = string
}

variable "administrator_login_password" {
  description = "admin password. generated by terraform. saved in keyvault_secret"
  type        = string
  sensitive   = true
}

variable "minimum_tls_version" {
  description = "Minimum TLS Version to use."
  type        = string
}
variable "database_name" {
  description = "Name of the MSSQL database to create."
  type        = string
}

variable "sku_name" {
  description = "Azure SQL SKU name (e.g. Basic, GP_S_Gen5_2)."
  type        = string
}

variable "max_size_gb" {
  description = "Max sotrage size of SQL"
  type        = string
}

variable "read_scale" {
  description = "Is sql read servers will be autoscaled"
  type        = bool
  default     = false
}

variable "geo_backup_enabled" {
  description = "Backup the database"
  type        = bool
  default     = true
}

variable "min_capacity" {
  description = "value"
  type        = string
  default     = null
}

variable "auto_pause_delay_in_minutes" {
  description = "pause instance after X amount of minutes"
  type        = number
  default     = null
}

variable "key_vault_id" {
  description = "ID of the Key Vaulr"
  type        = string
}

variable "admin_secret_name" {
  description = "The sql admin Secret name in KV"
  type        = string
}

variable "public_network_access_enabled" {
  description = "Enable public network"
  type = bool
  default = true
}


variable "private_endpoints" {
  description = "Map of logical name → subnet ID to create one private endpoint per subnet"
  type        = map(string)
  default     = {}
}