name: Build & Push to ACR

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (e.g., v1.0.0)'
        required: true
        default: 'v1.0.0'
  push:
    paths:
      - 'api-code/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v2
        with:
          login-server: varonishaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}


      - uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: varonishaacr.azurecr.io/restaurant-app:${{ github.event.inputs.tag }}
