name: Build & Push Image

on:
  push:
    paths:
      - 'restaurant_api/**'
jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v2
        with:
          login-server: varonishaacr.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./restaurant_api/.
          push: true
          tags: varonishaacr.azurecr.io/restaurant-app:${{github.run_number}}
